version: '3.8'

services:
  html2pdf:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 